# Generated by Django 4.0.4 on 2022-05-19 14:47

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_message', models.CharField(blank=True, max_length=100, null=True)),
                ('date_issued', models.DateField(default=django.utils.timezone.now)),
                ('groups', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.groups')),
                ('messages', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.message')),
                ('room', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='base.room')),
            ],
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_message', models.CharField(blank=True, max_length=100)),
                ('date_issued', models.DateTimeField(default=django.utils.timezone.now)),
                ('conversations', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.message')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.groups')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.room')),
                ('topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.topic')),
            ],
            options={
                'verbose_name_plural': 'Activities',
            },
        ),
    ]
